### ISSUE TITLE
SPFx 1.15.0-rc.0 - ENOENT: no such file or directory, open '/.../src/webparts/.../loc/lib.dom.d.js'

### ISSUE THREAD

**Issue by MarkusLanger** [s-KaiNet/spfx-check-locale#1]
I created a new SPFx project with the public preview version "1.15.0-rc.0". 
I get an error from spfx-check-locale.

![image](https://user-images.githubusercontent.com/12131918/173867306-7806b517-76da-4ca3-bef1-cf1ae1451300.png)

Steps to reproduce:
1. create a new SPFx project
2. add spfx-check-locale package and modify gulpfile as described => https://github.com/s-KaiNet/spfx-check-locale#how-to-use
3. run gulp build --ship

**Comment by s-KaiNet** [comment]
I've published version 0.0.4 with the fix.

Strange enough, but the fix was just to update dependencies. Anyway, I added additional checks to prevent this kind of error in the future (lib.dom.d.js is not even a part of the virtual check-locale TS build, I don't have any idea why it appears in the output). Please check if it works as expected for you.

**Comment by MarkusLanger** [comment]
Works very well. Thanks for the quick support.
